### ISSUE TITLE
solid-js/web may no longer have className

### ISSUE THREAD

**Issue by lominming** [vriteio/tiptap-solid#2] opened 2023-09-09 04:47 UTC
I'm hitting this error with v2023.7.25, solid-js^1.7.11, solid-start^0.3.5

`The requested module 'solid-js/web' does not provide an export named 'className'`

```
node_modules/@vrite/tiptap-solid/dist/esm/index.js:1
import { use, insert, effect, className, template, spread, createComponent, Portal, Dynamic, mergeProps } from 'solid-js/web';
                              ^^^^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'className'
```

**Comment by areknawo** [comment] 2023-09-09 06:50
Hey,
Can't really replicate this. Tried here:
https://stackblitz.com/edit/solidjs-templates-qspaj6?file=src%2FApp.tsx

I've updated the dependencies, so you can try updating to 1.0.0 (moving on from Beta date-versioning) though it likely won't help.

Wondering if this has something to do with Solid Start or other parts of your setup.

If the update doesn't help, I'd need a minimal reproducible example of the error to debug.

**Comment by areknawo** [comment] 2023-09-30 14:00
Hey there,

Since I couldn't replicate the problem, with no further feedback, I'll close this issue for now.

Feel free to reopen with a reproducible example if this happens again.

**Closed as completed by areknawo** 2023-09-30 14:00 UTC

**Comment by areknawo** [comment] 2023-11-17 10:00
This is an old issue, but recently I managed to accidentally reproduce it with [Astro](https://astro.build/) in SSR mode.

From what I understand from [this](https://github.com/solidjs/solid/issues/1480) (possibly related issue) is that different versions of Solid are loaded in different environments, where one lacks e.g. a `className` export.

The only solution I have for now is to load `@vrite/tiptap-solid` (and any other libraries with similar issues) only on the client-side, e.g. with async `import()` and `lazy()` components.

**Comment by dsmurl** [comment] 2023-12-12 20:50
@areknawo 
I believe this is because the calling app you are pulling this lib into, has a newer version of solid-js.  My application gets this error because I'm on solid-js 1.8 and this taiptap-solid has a peer dep of ^1.7.  I believe in 1.7 the /web had className (tho deprecated) and they removed it in 1.8.  This lib may not work with current version of solid-js.  Downgrading your app to fit 1.7 is probably not a good idea either.  ClassName was deprecated in 1.4 and could/should be removed if this lib is wanting 1.7 as a peerDep -> https://github.com/solidjs/solid/blob/main/CHANGELOG.md#classname-htmlfor-deprecated

**Comment by areknawo** [comment] 2023-12-12 20:58
@dsmurl I'm currently using it with Solid.js v1.8.7 and Vite in Vrite (SPA), with no issues. Also, the issue was opened before v1.8 was released.

What I've said in the previous comment is more likely - Solid provides different exports for server and client. I haven't experienced the issue in SPA, but I did so in Astro and Solid Start (SSR).

**Comment by dsmurl** [comment] 2023-12-12 22:22
Thanks, I just lazy loaded it and I'm moving.  I think I'm on the same path as @lominming .  I want to get Mentions working.
